<a href="https://colab.research.google.com/github/syotakokichi/Jackie/blob/Python/5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math# importは大抵セルの一番上に記述します
print(math.sqrt(2)) # sqrt は平方根を計算する関数
print(math.pi) # πの値
print(math.sin(math.pi/4)) # sin関数
print(math.cos(0)) # cos関数
print(math.log(32,2)) # 2を底とする32の対数（texで記述すると、$\log_2 32$）

1.4142135623730951
3.141592653589793
0.7071067811865475
1.0
5.0


In [2]:
math.pi

3.141592653589793

In [3]:
from math import sqrt
print(sqrt(2)) # sqrt は平方根を計算する関数
from math import pi
print(pi) # πの値
from math import sin
print(sin(math.pi/4)) # sin関数
from math import cos
print(cos(0)) # cos関数
from math import log
print(log(32,2)) # 2を底とする32の対数（texで記述すると、$\log_2 32$）

1.4142135623730951
3.141592653589793
0.7071067811865475
1.0
5.0


In [4]:
from math import *

In [5]:
from math import *
print(factorial(5)) # 5 の階乗 # import mathを使う場合、math.factorial(5)
print(floor(2.31)) # 2.31以下の最大の整数  # import mathを使う場合、math.floor(2.31)
print(e) # ネイピア数 # import mathを使う場合、math.e

120
2
2.718281828459045


In [6]:
import numpy
print(numpy.ones((3, 5))) # 3×5の行列を表示
import numpy as np
print(np.ones((3, 5))) # np という短い名称で同じ関数を利用する

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
import math
print(math.factorial(5)) # 階乗を求める関数factorial # 5の階乗
from math import factorial as fact # fact という名前でmath.factorialを使用したい
print(fact(5))

120
120


In [8]:
import math
print(math.sqrt(2))
print(math.sin(math.pi))

1.4142135623730951
1.2246467991473532e-16


In [9]:
print(sqrt(2))
print(sin(pi))

1.4142135623730951
1.2246467991473532e-16


In [10]:
import
print(sqrt(2))
print(sin(pi))

SyntaxError: invalid syntax (<ipython-input-10-60c6e0f97faa>, line 1)

In [11]:
from math import sqrt, sin, pi
print(sqrt(2))
print(sin(pi))

1.4142135623730951
1.2246467991473532e-16
