<a href="https://colab.research.google.com/github/syotakokichi/Jackie/blob/Python/5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3]) # リストから配列作成
print(a)
b = np.array((1,2,3)) # タプルからの配列作成
print(b)

[1 2 3]
[1 2 3]


In [3]:
a

array([1, 2, 3])

In [4]:
b

array([1, 2, 3])

In [5]:
type(np.array([1,2,3,4,5])) # 配列の型

numpy.ndarray

In [6]:
type([1,2,3,4,5])

list

In [7]:
print(np.array([-1,0,1], dtype=np.int32)) # np.int32の代わりに'int32'でも同じ

[-1  0  1]


In [8]:
print(np.array([-1,0,1], dtype=np.float64)) # np.float64の代わりに'float64'でも同じ

[-1.  0.  1.]


In [9]:
print(np.array([-1,0,1], dtype=np.complex128)) # np.complex128の代わりに'complex128'でも同じ

[-1.+0.j  0.+0.j  1.+0.j]


In [10]:
print(np.array([[1,2],[3,4]])) # 2次元配列の構築

[[1 2]
 [3 4]]


In [11]:
print(np.array([[[1,2],[3,4]],[[5,6],[7,8]]])) # 3次元配列の構築

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
print(np.array([[1,2],[3]])) # 行の長さが異なる場合


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [13]:
a1 = np.array([0, 1, 2, 3, 4, 5]) # 1次元配列
a2

NameError: name 'a2' is not defined

In [14]:
a1[1] = 6
print(a1)
print(a2)

[0 6 2 3 4 5]


NameError: name 'a2' is not defined

In [15]:
a1 = np.array([0, 1, 2, 3, 4, 5]) # 1次元配列
a2 = a1.reshape(2,3)              # 2×3の2次元配列
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
a1[1] = 6
print(a1)
print(a2)

[0 6 2 3 4 5]
[[0 6 2]
 [3 4 5]]


In [17]:
a = np.array([0, 1, 2, 3, 4, 5]).reshape(2,3)
print(a)
print(a.ravel())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [18]:
elems = np.array([0, 1, 2, 3, 4, 5])
a = elems.reshape(2,3).ravel() # ravel()は要素をelemsと共有
elems[1] = 6
print(a)


[0 6 2 3 4 5]


In [19]:
print(np.linspace(0, 1, 4)) # 0から1の値を4分割した値を要素に持つ配列

[0.         0.33333333 0.66666667 1.        ]


In [20]:
print(np.zeros(4))     # 長さ4の1次元配列
print(np.zeros((2,3))) # 2×3の2次元配列を生成
print(np.ones(4))     # 長さ4の1次元配列
print(np.ones((2,3))) # 2×3の2次元配列を生成

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
print(np.random.rand(4))   # 長さ4の1次元配列
print(np.random.rand(2,3)) # 2×3の2次元配列を生成

[0.56028028 0.55364517 0.62404159 0.83414291]
[[0.9580019  0.72294103 0.01459762]
 [0.72515552 0.42493047 0.58992842]]


In [22]:
range_square_matrix(3)

NameError: name 'range_square_matrix' is not defined

In [23]:
[[0 1 2]
 [1 2 3]
 [2 3 4]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-23-7c5bfec8bbe6>, line 1)

In [24]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))


NameError: name 'arange_square_matrix' is not defined

In [25]:
a = np.arange(3)
print(a)

[0 1 2]


In [26]:
a[-1] = 3 # 要素への代入もできる
print(a)

[0 1 3]


In [27]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [28]:
a[1,2]

5

In [29]:
a[1,2] = 6 # 要素への代入もできる
print(a)

[[0 1 2]
 [3 4 6]]


In [30]:
a = np.arange(5)
print(a)
print(a[1:4])
print(a[1:])
print(a[:-2])
print(a[::2])
print(a[::-1])

[0 1 2 3 4]
[1 2 3]
[1 2 3 4]
[0 1 2]
[0 2 4]
[4 3 2 1 0]


In [31]:
a = np.arange(5)
print(a)
a[1:4] = 6
print(a)
a = np.arange(5)
a[::2] = 6
print(a)

[0 1 2 3 4]
[0 6 6 6 4]
[6 1 6 3 6]


In [35]:
a = [0,1,2,3,4]
print(a)
a[1:4] = [6]
print(a)

[0, 1, 2, 3, 4]
[0, 6, 4]


In [36]:
for row in np.arange(6).reshape(2,3):
    print(row)

[0 1 2]
[3 4 5]


In [37]:
for idx, e in np.ndenumerate(np.arange(6).reshape(2,3)):
    print(idx, e)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5


In [38]:
for idx, e in np.ndenumerate(np.arange(3)):
    print(idx, e)

(0,) 0
(1,) 1
(2,) 2


In [39]:
a = np.arange(4)
print(a)

print(a + 1) # 各要素に1を加算
print(a - 1) # 各要素に1を減算
print(a * 2) # 各要素に2を乗算
print(a / 2) # 各要素を2で除算
print(a // 2) # 各要素を2で整数除算
print(a % 2) # 各要素に2の剰余演算
print(a ** 2) # 各要素を2乗

print(1 + a) # 左側がスカラでもよい
print(1 - a) # 左側がスカラでもよい
print(2 * a) # 左側がスカラでもよい
b = a + 1
print(1 / b) # 左側がスカラでもよい
print(9 // b) # 左側がスカラでもよい

[0 1 2 3]
[1 2 3 4]
[-1  0  1  2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[0 1 0 1]
[0 1 4 9]
[1 2 3 4]
[ 1  0 -1 -2]
[0 2 4 6]
[1.         0.5        0.33333333 0.25      ]
[9 4 3 2]


In [40]:
a = np.arange(4).reshape(2,2)
b = np.arange(1,5).reshape(2,2)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)
c = 3 * a
print(c // b)
print(a % b)
print(a ** b)

[[0 1]
 [2 3]]
[[1 2]
 [3 4]]
[[1 3]
 [5 7]]
[[-1 -1]
 [-1 -1]]
[[ 0  2]
 [ 6 12]]
[[0.         0.5       ]
 [0.66666667 0.75      ]]
[[0 1]
 [2 2]]
[[0 1]
 [2 3]]
[[ 0  1]
 [ 8 81]]


In [41]:
a = np.zeros(3) + 2
print(a)
print(np.sqrt(a)) # 各要素はsqrt(2)
b = np.zeros((2,2)) + 2
print(np.sqrt(b)) # 各要素はsqrt(2)
print(np.sqrt(2)) # スカラ（0次元配列）も扱える

[2. 2. 2.]
[1.41421356 1.41421356 1.41421356]
[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]
1.4142135623730951


In [42]:
np.dot(np.arange(4), np.arange(1,5)) # 0*1 + 1*2 + 2*3 + 3*4

20

In [43]:
# [[0 1]     [[1 2]
#  [2 3]] と  [3 4]] の行列積
print(np.dot(np.arange(4).reshape(2,2), np.arange(1,5).reshape(2,2)))

[[ 3  4]
 [11 16]]


In [44]:
a = np.array([3, 4, -1, 0, 2])
print(a)
print(np.sort(a))

[ 3  4 -1  0  2]
[-1  0  2  3  4]


In [45]:
a = np.array([3, 4, -1, 0, 2])
print(a)
a.sort()
print(a)

[ 3  4 -1  0  2]
[-1  0  2  3  4]


In [46]:
a = np.arange(6).reshape(2,3)
print(a)
print(a.sum())
print(a.sum(0))
print(a.sum(1))

[[0 1 2]
 [3 4 5]]
15
[3 5 7]
[ 3 12]


In [47]:
np.savetxt('arange3.txt', np.arange(3))

In [49]:
np.savetxt('arange2x3.txt', np.arange(6).reshape(2,3))

In [50]:
a = np.loadtxt('arange2x3.txt')
print(a)

[[0. 1. 2.]
 [3. 4. 5.]]


In [51]:
a = np.arange(6)
print(a)
print(a < 3)

[0 1 2 3 4 5]
[ True  True  True False False False]


In [52]:
a = np.array([0,1,2,-3,-4,5,-6,-7])
print(a)
print(a[a < 0]) # 負の要素を取り出し
print(a[(a < 0) & (a % 2 == 0)]) # 負で偶数の要素を取り出し
a[a < 0] = 8 # 負の要素を8に上書き
print(a)

[ 0  1  2 -3 -4  5 -6 -7]
[-3 -4 -6 -7]
[-4 -6]
[0 1 2 8 8 5 8 8]


In [54]:
I = np.identity(3)
print(I)
a = np.arange(9).reshape(3,3)
print(a)
print(np.matmul(a, I))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [55]:
np.linalg.norm(np.ones(3)) # ユークリッドノルムを計算するのでsqrt(3)と等しい

1.7320508075688772